In [176]:
import numpy as np
import pandas as pd

In [177]:
df=pd.read_csv('/content/Attrition.csv')

In [178]:
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [179]:
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.metrics import accuracy_score

In [180]:
df.columns

Index(['Age', 'Attrition', 'BusinessTravel', 'DailyRate', 'Department',
       'DistanceFromHome', 'Education', 'EducationField', 'EmployeeCount',
       'EmployeeNumber', 'EnvironmentSatisfaction', 'Gender', 'HourlyRate',
       'JobInvolvement', 'JobLevel', 'JobRole', 'JobSatisfaction',
       'MaritalStatus', 'MonthlyIncome', 'MonthlyRate', 'NumCompaniesWorked',
       'Over18', 'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'StandardHours', 'StockOptionLevel',
       'TotalWorkingYears', 'TrainingTimesLastYear', 'WorkLifeBalance',
       'YearsAtCompany', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager'],
      dtype='object')

In [181]:
df=df.dropna()

In [182]:
x=df.drop(columns=['Attrition'],axis=1)
y=df['Attrition']

In [183]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

In [184]:
categorical_features=['BusinessTravel','Department','EducationField','Gender','JobRole','MaritalStatus','Over18','OverTime']

In [185]:
categorical_features

['BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

In [186]:
x_encoded=pd.get_dummies(x,columns=categorical_features,drop_first=True)

In [187]:
x_encoded.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,False,False,False,False,False,True,False,False,True,True
1,49,279,8,1,1,2,3,61,2,2,...,False,False,False,False,True,False,False,True,False,False
2,37,1373,2,2,1,4,4,92,2,1,...,True,False,False,False,False,False,False,False,True,True
3,33,1392,3,4,1,5,4,56,3,1,...,False,False,False,False,True,False,False,True,False,True
4,27,591,2,1,1,7,1,40,3,1,...,True,False,False,False,False,False,False,True,False,False

In [188]:
x_encoded

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,False,False,False,False,False,True,False,False,True,True
1,49,279,8,1,1,2,3,61,2,2,...,False,False,False,False,True,False,False,True,False,False
2,37,1373,2,2,1,4,4,92,2,1,...,True,False,False,False,False,False,False,False,True,True
3,33,1392,3,4,1,5,4,56,3,1,...,False,False,False,False,True,False,False,True,False,True
4,27,591,2,1,1,7,1,40,3,1,...,True,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,884,23,2,1,2061,3,41,4,2,...,True,False,False,False,False,False,False,True,False,False
1466,39,613,6,1,1,2062,4,42,2,3,...,False,False,False,False,False,False,False,True,False,False
1467,27,155,4,3,1,2064,2,87,4,2,...,False,False,True,False,False,False,False,True,False,True
1468,49,1023,2,3,1,2065,4,63,2,2,...,False,False,False,False,False,True,False,True,False,False
1469,34,628,8,3,1,2068,2,82,4,2,...,True,False,False,False,False,False,False,True,False,False

encode target data

In [189]:
lb=LabelEncoder()

In [190]:
y_encoded=lb.fit_transform(y)

In [191]:
y_encoded

array([1, 0, 1, ..., 0, 0, 0])

In [192]:
x_train,x_test,y_train,y_test=train_test_split(x_encoded,y_encoded,test_size=0.2,random_state=42)

In [193]:
x_train.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Married,MaritalStatus_Single,OverTime_Yes
1097,24,350,21,2,1,1551,3,57,2,1,...,True,False,False,False,False,False,False,False,False,False
727,18,287,5,2,1,1012,2,73,3,1,...,False,False,False,False,True,False,False,False,True,False
254,29,1247,20,2,1,349,4,45,3,2,...,False,False,False,False,False,True,False,False,False,False
1175,39,492,12,3,1,1654,4,66,3,2,...,False,False,True,False,False,False,False,True,False,False
1341,31,311,20,3,1,1881,2,89,3,2,...,True,False,False,False,False,False,False,False,False,False

In [194]:
y_train

array([0, 0, 0, ..., 1, 0, 0])

NORMAL DISTRIBUTION CONVERTION

In [195]:
sc=StandardScaler()

In [196]:
x_train_scaled=sc.fit_transform(x_train)
x_test_scaled=sc.transform(x_test)

In [197]:
x_train_scaled.shape

(1176, 47)

In [198]:
y_train.shape

(1176,)

# NOW WE WILL CREATE ARCHITECTURE OF OUR MODEL

In [199]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=128,activation='relu',
                          input_dim=x_train_scaled.shape[1]), # input layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=64,activation='relu'), # hidden layer
    tf.keras.layers.Dropout(0.3),
    tf.keras.layers.Dense(units=1,activation='sigmoid') # output layer
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

# COMPILE THE MODEL

In [200]:
# LOSE FUNCTION =>PREDICATION - REAL
loss_fn=tf.keras.losses.BinaryCrossentropy()
metrics=['accuracy']

In [201]:
learning_rate=0.001
momentum=0.9
optimizer=tf.keras.optimizers.SGD(learning_rate=learning_rate,momentum=momentum,nesterov=True) # nesterov => nestro evolation gradient

In [202]:
model.compile(optimizer=optimizer,loss=loss_fn,metrics=metrics)

# TRAIN THE MODEL

In [203]:
model.fit(x_train_scaled,
          y_train,
          epochs=50,
          batch_size=8,
          validation_split=0.1
          )

Epoch 1/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 3s 13ms/step - accuracy: 0.6264 - loss: 0.6696 - val_accuracy: 0.7966 - val_loss: 0.5162
Epoch 2/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - accuracy: 0.8404 - loss: 0.4419 - val_accuracy: 0.7966 - val_loss: 0.4828
Epoch 3/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8074 - loss: 0.4624 - val_accuracy: 0.7966 - val_loss: 0.4680
Epoch 4/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8462 - loss: 0.3976 - val_accuracy: 0.7966 - val_loss: 0.4518
Epoch 5/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8534 - loss: 0.3695 - val_accuracy: 0.8051 - val_loss: 0.4415
Epoch 6/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8532 - loss: 0.3791 - val_accuracy: 0.8051 - val_loss: 0.4358
Epoch 7/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8419 - loss: 0.3760 - val_accuracy: 0.7966 - val_loss: 0.4290
Epoch 8/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8473 - loss: 0.3695 - val_accuracy: 0.7966 - val_loss: 0.4248
Epoch 9/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8533 - loss: 0.3535 - val_accuracy: 0.8051 - val_loss: 0.4198
Epoch 10/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8489 - loss: 0.3350 - val_accuracy: 0.8051 - val_loss: 0.4187
Epoch 11/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8585 - loss: 0.3047 - val_accuracy: 0.8051 - val_loss: 0.4160
Epoch 12/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8694 - loss: 0.2957 - val_accuracy: 0.7966 - val_loss: 0.4110
Epoch 13/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8642 - loss: 0.3381 - val_accuracy: 0.8136 - val_loss: 0.4120
Epoch 14/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8800 - loss: 0.3037 - val_accuracy: 0.8136 - val_loss: 0.4118
Epoch 15/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8831 - loss: 0.2807 - val_accuracy: 0.8220 - val_loss: 0.4082
Epoch 16/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8781 - loss: 0.3075 - val_accuracy: 0.8220 - val_loss: 0.4107
Epoch 17/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8953 - loss: 0.2949 - val_accuracy: 0.8220 - val_loss: 0.4110
Epoch 18/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8832 - loss: 0.2782 - val_accuracy: 0.8305 - val_loss: 0.4092
Epoch 19/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8904 - loss: 0.2795 - val_accuracy: 0.8220 - val_loss: 0.4058
Epoch 20/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8832 - loss: 0.2826 - val_accuracy: 0.8220 - val_loss: 0.4119
Epoch 21/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8696 - loss: 0.3029 - val_accuracy: 0.8305 - val_loss: 0.4134
Epoch 22/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8967 - loss: 0.2628 - val_accuracy: 0.8220 - val_loss: 0.4122
Epoch 23/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8946 - loss: 0.2604 - val_accuracy: 0.8305 - val_loss: 0.4150
Epoch 24/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9003 - loss: 0.2312 - val_accuracy: 0.8390 - val_loss: 0.4073
Epoch 25/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9067 - loss: 0.2421 - val_accuracy: 0.8390 - val_loss: 0.4071
Epoch 26/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8897 - loss: 0.2697 - val_accuracy: 0.8305 - val_loss: 0.4073
Epoch 27/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8945 - loss: 0.2341 - val_accuracy: 0.8305 - val_loss: 0.4112
Epoch 28/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9048 - loss: 0.2447 - val_accuracy: 0.8305 - val_loss: 0.4139
Epoch 29/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8941 - loss: 0.2864 - val_accuracy: 0.8220 - val_loss: 0.4148
Epoch 30/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9040 - loss: 0.2335 - val_accuracy: 0.8220 - val_loss: 0.4127
Epoch 31/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9092 - loss: 0.2427 - val_accuracy: 0.8220 - val_loss: 0.4213
Epoch 32/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9069 - loss: 0.2142 - val_accuracy: 0.8305 - val_loss: 0.4239
Epoch 33/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8970 - loss: 0.2435 - val_accuracy: 0.8220 - val_loss: 0.4197
Epoch 34/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9116 - loss: 0.2281 - val_accuracy: 0.8390 - val_loss: 0.4274
Epoch 35/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9255 - loss: 0.1798 - val_accuracy: 0.8305 - val_loss: 0.4247
Epoch 36/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9158 - loss: 0.2204 - val_accuracy: 0.8305 - val_loss: 0.4296
Epoch 37/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9250 - loss: 0.1990 - val_accuracy: 0.8220 - val_loss: 0.4380
Epoch 38/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9231 - loss: 0.2083 - val_accuracy: 0.8220 - val_loss: 0.4308
Epoch 39/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9110 - loss: 0.2136 - val_accuracy: 0.8475 - val_loss: 0.4263
Epoch 40/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9183 - loss: 0.2073 - val_accuracy: 0.8390 - val_loss: 0.4365
Epoch 41/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9026 - loss: 0.2083 - val_accuracy: 0.8220 - val_loss: 0.4394
Epoch 42/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9260 - loss: 0.1928 - val_accuracy: 0.8220 - val_loss: 0.4441
Epoch 43/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9027 - loss: 0.2122 - val_accuracy: 0.8305 - val_loss: 0.4395
Epoch 44/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9188 - loss: 0.1966 - val_accuracy: 0.8305 - val_loss: 0.4374
Epoch 45/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9024 - loss: 0.2192 - val_accuracy: 0.8220 - val_loss: 0.4453
Epoch 46/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9347 - loss: 0.1851 - val_accuracy: 0.8220 - val_loss: 0.4432
Epoch 47/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9351 - loss: 0.1720 - val_accuracy: 0.8305 - val_loss: 0.4540
Epoch 48/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9150 - loss: 0.1946 - val_accuracy: 0.8305 - val_loss: 0.4651
Epoch 49/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9177 - loss: 0.1853 - val_accuracy: 0.8220 - val_loss: 0.4546
Epoch 50/50
133/133 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9263 - loss: 0.1976 - val_accuracy: 0.8305 - val_loss: 0.4674

In [206]:
loss,accuracy=model.evaluate(x_test_scaled,y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8394 - loss: 0.4355

In [207]:
print(f'Test Loss ={loss:.4f},Test Accuracy = {accuracy:.4f}')

Test Loss =0.3979,Test Accuracy = 0.8571

In [1]:
print(f'Test Loss ={loss},Test Accuracy = {accuracy}')

NameError: name 'loss' is not defined

In [ ]:
# EPOCH
# One epoch = one full pass over the entire training dataset.

# You define how many epochs the model should train (e.g. 50).

# ITERATION
# One iteration = one update of the model’s weights.

# Happens once per batch.